# Module: UnitTests.SmokeTest.py
# Version: 0.1
# Author: Aaron Sharp
# Date: 07/23/2015
# 
# The purpose of this module is to provide integration tests for 
# all modules in  Operations.Assemble.BioNano
import unittest
import os
from copy import copy
import shutil
import StringIO
import sys
from Utils.Workspace import Workspace
from Operations.SBATCHCodeFormatter import CodeFormatter
from Operations.BioNano.Assemble.Assembly import Assembly
from Operations.BioNano.Assemble.PairwiseAlignment import PairwiseAlignment
from Operations.BioNano.Assemble.Split import Split
from Operations.BioNano.Assemble.Sort import Sort
from Operations.BioNano.Assemble.VitalParameters import VitalParameters
from Operations.BioNano.Parameterize.ParameterSearch import ParameterSearch

class SmokeTest(unittest.TestCase):
	workspace=Workspace("test_work_dir", "input.bnx")
	vital_parameters=VitalParameters(1.5, .150, 1e-5, 100, 6)
	formatter=CodeFormatter()
	native_stdout=sys.stdout
	def setUp(self):
		os.mkdir(self.workspace.work_dir)
		with open(self.workspace.work_dir + "/" + self.workspace.input_file, "w") as bnx_file:
			bnx_file.write("\n".join([
				"# BNX File Version:	1.2", 
				"#0h	LabelChannel	MoleculeId	Length	AvgIntensity	SNR	NumberofLabels	OriginalMoleculeId	ScanNumber	ScanDirection	ChipId	Flowcell	RunId	GlobalScanNumber",
				"#0f	int	int	float	float	float	int	int	int	int	string	int	int	int",
				"#1h	LabelChannel	LabelPositions[N]",
				"#1f	int	float",
				"#2h	LabelChannel	LabelPositions[N]",
				"#2h	int	float",
				"#Qh	QualityScoreID	QualityScores[N]",
				"#Qf	str	float",
				"0	1	11915.3	0.064331	39.060	7	1	1	-1	20249,11731,11/25/2013,840012494	1	1	1",
				"1	0.0	3785.6	5068.4	7060.8	7968.7	7987.8	11267.0	11915.3",
				"QX11	0.6905	0.8113	0.5751	1.4108	2.2148	1.1966	0.8701",
				"QX12	0.0327	0.0330	0.0328	0.0342	0.0349	0.0341	0.0334"
			]))
		self.workspace.addBinary("bng_assembler", "path/to/Assembler")
		self.workspace.addBinary("bng_ref_aligner", "path/to/RefAligner")

		self.buffer_stdout=StringIO.StringIO()
		sys.stdout=self.buffer_stdout

	def tearDown(self):
		self.buffer_stdout.close()
		sys.stdout=self.native_stdout

		shutil.rmtree(self.workspace.work_dir)

	def dummy_returnTrue(self):
		return True
	def dummy_returnFalse(self):
		return False

	def test_writeCode_sort(self):
		step=Sort(self.workspace, copy(self.vital_parameters))
		expected="\n".join(["#!/bin/bash",
			"",
			"",
			"step1=\"-d afterok\"",
			"sresult=`sbatch  step1_part1.sh`",
			"echo $sresult",
			"sid=`echo $sresult | awk '{print $NF}'`",
			"step1=$step1:$sid",
			""
			])

		self.formatter.runOneStep(step)

		self.assertEqual(expected, self.buffer_stdout.getvalue())

	def test_writeCode_sort_isComplete(self):
		native_isComplete=Sort.isComplete
		Sort.isComplete=self.dummy_returnTrue.im_func
		step=Sort(self.workspace, copy(self.vital_parameters))
		expected="\n".join(["#!/bin/bash",
			"",
			""
			])


		self.formatter.runOneStep(step)

		Sort.isComplete=native_isComplete

		self.assertEqual(expected, self.buffer_stdout.getvalue())

	def test_writeCode_assembly(self):
		step=Assembly(self.workspace, copy(self.vital_parameters))
		
		expected="\n".join(["#!/bin/bash",
				"",
				"",
				"step1=\"-d afterok\"",
				"sresult=`sbatch  step1_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"step1=$step1:$sid",
				"",
				"step2=\"-d afterok\"",
				"sresult=`sbatch $step1 step2_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"step2=$step2:$sid",
				"",
				"step3=\"-d afterok\"",
				"sresult=`sbatch $step2 step3_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"step3=$step3:$sid",
				"",
				"step4=\"-d afterok\"",
				"sresult=`sbatch $step3 step4_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"step4=$step4:$sid",
				"",
				"step5=\"-d afterok\"",
				"sresult=`sbatch $step4 step5_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"step5=$step5:$sid",
				"",
				"step6=\"-d afterok\"",
				"sresult=`sbatch $step5 step6_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"step6=$step6:$sid",
				""
				])
		
		self.formatter.runOneStep(step)

		self.assertEqual(expected, self.buffer_stdout.getvalue())

	def test_parameterSearch(self):
		search=ParameterSearch(self.workspace, 900)
		expected="\n".join([
				"#!/bin/bash",
				"",
				"",
				"level1_step1=\"-d afterok\"",
				"sresult=`sbatch  level1_step1_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level1_step1=$level1_step1:$sid",
				"",
				"level2_step1=\"-d afterok\"",
				"sresult=`sbatch $level1_step1 level2_step1_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level2_step1=$level2_step1:$sid",
				"",
				"level3_step1=\"-d afterok\"",
				"sresult=`sbatch $level2_step1 level3_step1_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level3_step1=$level3_step1:$sid",
				"",
				"level4_step1=\"-d afterok\"",
				"sresult=`sbatch  level4_step1_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level4_step1=$level4_step1:$sid",
				"",
				"level4_step2=\"-d afterok\"",
				"sresult=`sbatch  level4_step2_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level4_step2=$level4_step2:$sid",
				"",
				"level4_step3=\"-d afterok\"",
				"sresult=`sbatch  level4_step3_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level4_step3=$level4_step3:$sid",
				"",
				"level4_step4=\"-d afterok\"",
				"sresult=`sbatch  level4_step4_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level4_step4=$level4_step4:$sid",
				"",
				"level4_step5=\"-d afterok\"",
				"sresult=`sbatch  level4_step5_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level4_step5=$level4_step5:$sid",
				"",
				"level4_step6=\"-d afterok\"",
				"sresult=`sbatch  level4_step6_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level4_step6=$level4_step6:$sid",
				"",
				"level4_step7=\"-d afterok\"",
				"sresult=`sbatch  level4_step7_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level4_step7=$level4_step7:$sid",
				"",
				"level4_step8=\"-d afterok\"",
				"sresult=`sbatch  level4_step8_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level4_step8=$level4_step8:$sid",
				"",
				"level4_step9=\"-d afterok\"",
				"sresult=`sbatch  level4_step9_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level4_step9=$level4_step9:$sid",
				"",
				"level5_step1=\"-d afterok\"",
				"sresult=`sbatch $level4_step7 level5_step1_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level5_step1=$level5_step1:$sid",
				"",
				"level5_step2=\"-d afterok\"",
				"sresult=`sbatch $level4_step8 level5_step2_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level5_step2=$level5_step2:$sid",
				"",
				"level5_step3=\"-d afterok\"",
				"sresult=`sbatch $level4_step9 level5_step3_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level5_step3=$level5_step3:$sid",
				"",
				"level5_step4=\"-d afterok\"",
				"sresult=`sbatch $level4_step1 level5_step4_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level5_step4=$level5_step4:$sid",
				"",
				"level5_step5=\"-d afterok\"",
				"sresult=`sbatch $level4_step5 level5_step5_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level5_step5=$level5_step5:$sid",
				"",
				"level5_step6=\"-d afterok\"",
				"sresult=`sbatch $level4_step3 level5_step6_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level5_step6=$level5_step6:$sid",
				"",
				"level5_step7=\"-d afterok\"",
				"sresult=`sbatch $level4_step2 level5_step7_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level5_step7=$level5_step7:$sid",
				"",
				"level5_step8=\"-d afterok\"",
				"sresult=`sbatch $level4_step4 level5_step8_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level5_step8=$level5_step8:$sid",
				"",
				"level5_step9=\"-d afterok\"",
				"sresult=`sbatch $level4_step6 level5_step9_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level5_step9=$level5_step9:$sid",
				"",
				"level6_step1=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step1_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step1=$level6_step1:$sid",
				"",
				"level6_step2=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step2_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step2=$level6_step2:$sid",
				"",
				"level6_step3=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step3_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step3=$level6_step3:$sid",
				"",
				"level6_step4=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step4_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step4=$level6_step4:$sid",
				"",
				"level6_step5=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step5_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step5=$level6_step5:$sid",
				"",
				"level6_step6=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step6_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step6=$level6_step6:$sid",
				"",
				"level6_step7=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step7_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step7=$level6_step7:$sid",
				"",
				"level6_step8=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step8_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step8=$level6_step8:$sid",
				"",
				"level6_step9=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step9_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step9=$level6_step9:$sid",
				"",
				"level6_step10=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step10_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step10=$level6_step10:$sid",
				"",
				"level6_step11=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step11_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step11=$level6_step11:$sid",
				"",
				"level6_step12=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step12_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step12=$level6_step12:$sid",
				"",
				"level6_step13=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step13_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step13=$level6_step13:$sid",
				"",
				"level6_step14=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step14_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step14=$level6_step14:$sid",
				"",
				"level6_step15=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step15_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step15=$level6_step15:$sid",
				"",
				"level6_step16=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step16_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step16=$level6_step16:$sid",
				"",
				"level6_step17=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step17_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step17=$level6_step17:$sid",
				"",
				"level6_step18=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step18_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step18=$level6_step18:$sid",
				"",
				"level6_step19=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step19_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step19=$level6_step19:$sid",
				"",
				"level6_step20=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step20_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step20=$level6_step20:$sid",
				"",
				"level6_step21=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step21_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step21=$level6_step21:$sid",
				"",
				"level6_step22=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step22_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step22=$level6_step22:$sid",
				"",
				"level6_step23=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step23_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step23=$level6_step23:$sid",
				"",
				"level6_step24=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step24_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step24=$level6_step24:$sid",
				"",
				"level6_step25=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step25_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step25=$level6_step25:$sid",
				"",
				"level6_step26=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step26_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step26=$level6_step26:$sid",
				"",
				"level6_step27=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step27_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step27=$level6_step27:$sid",
				"",
				"level6_step28=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step28_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step28=$level6_step28:$sid",
				"",
				"level6_step29=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step29_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step29=$level6_step29:$sid",
				"",
				"level6_step30=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step30_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step30=$level6_step30:$sid",
				"",
				"level6_step31=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step31_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step31=$level6_step31:$sid",
				"",
				"level6_step32=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step32_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step32=$level6_step32:$sid",
				"",
				"level6_step33=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step33_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step33=$level6_step33:$sid",
				"",
				"level6_step34=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step34_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step34=$level6_step34:$sid",
				"",
				"level6_step35=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step35_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step35=$level6_step35:$sid",
				"",
				"level6_step36=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step36_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step36=$level6_step36:$sid",
				"",
				"level6_step37=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step37_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step37=$level6_step37:$sid",
				"",
				"level6_step38=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step38_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step38=$level6_step38:$sid",
				"",
				"level6_step39=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step39_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step39=$level6_step39:$sid",
				"",
				"level6_step40=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step40_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step40=$level6_step40:$sid",
				"",
				"level6_step41=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step41_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step41=$level6_step41:$sid",
				"",
				"level6_step42=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step42_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step42=$level6_step42:$sid",
				"",
				"level6_step43=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step43_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step43=$level6_step43:$sid",
				"",
				"level6_step44=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step44_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step44=$level6_step44:$sid",
				"",
				"level6_step45=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step45_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step45=$level6_step45:$sid",
				"",
				"level6_step46=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step46_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step46=$level6_step46:$sid",
				"",
				"level6_step47=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step47_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step47=$level6_step47:$sid",
				"",
				"level6_step48=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step48_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step48=$level6_step48:$sid",
				"",
				"level6_step49=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step49_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step49=$level6_step49:$sid",
				"",
				"level6_step50=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step50_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step50=$level6_step50:$sid",
				"",
				"level6_step51=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step51_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step51=$level6_step51:$sid",
				"",
				"level6_step52=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step52_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step52=$level6_step52:$sid",
				"",
				"level6_step53=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step53_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step53=$level6_step53:$sid",
				"",
				"level6_step54=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step54_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step54=$level6_step54:$sid",
				"",
				"level6_step55=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step55_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step55=$level6_step55:$sid",
				"",
				"level6_step56=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step56_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step56=$level6_step56:$sid",
				"",
				"level6_step57=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step57_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step57=$level6_step57:$sid",
				"",
				"level6_step58=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step58_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step58=$level6_step58:$sid",
				"",
				"level6_step59=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step59_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step59=$level6_step59:$sid",
				"",
				"level6_step60=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step60_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step60=$level6_step60:$sid",
				"",
				"level6_step61=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step61_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step61=$level6_step61:$sid",
				"",
				"level6_step62=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step62_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step62=$level6_step62:$sid",
				"",
				"level6_step63=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step63_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step63=$level6_step63:$sid",
				"",
				"level6_step64=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step64_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step64=$level6_step64:$sid",
				"",
				"level6_step65=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step65_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step65=$level6_step65:$sid",
				"",
				"level6_step66=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step66_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step66=$level6_step66:$sid",
				"",
				"level6_step67=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step67_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step67=$level6_step67:$sid",
				"",
				"level6_step68=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step68_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step68=$level6_step68:$sid",
				"",
				"level6_step69=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step69_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step69=$level6_step69:$sid",
				"",
				"level6_step70=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step70_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step70=$level6_step70:$sid",
				"",
				"level6_step71=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step71_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step71=$level6_step71:$sid",
				"",
				"level6_step72=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step72_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step72=$level6_step72:$sid",
				"",
				"level6_step73=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step73_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step73=$level6_step73:$sid",
				"",
				"level6_step74=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step74_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step74=$level6_step74:$sid",
				"",
				"level6_step75=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step75_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step75=$level6_step75:$sid",
				"",
				"level6_step76=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step76_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step76=$level6_step76:$sid",
				"",
				"level6_step77=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step77_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step77=$level6_step77:$sid",
				"",
				"level6_step78=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step78_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step78=$level6_step78:$sid",
				"",
				"level6_step79=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step79_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step79=$level6_step79:$sid",
				"",
				"level6_step80=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step80_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step80=$level6_step80:$sid",
				"",
				"level6_step81=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step81_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step81=$level6_step81:$sid",
				"",
				"level6_step82=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step82_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step82=$level6_step82:$sid",
				"",
				"level6_step83=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step83_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step83=$level6_step83:$sid",
				"",
				"level6_step84=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step84_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step84=$level6_step84:$sid",
				"",
				"level6_step85=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step85_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step85=$level6_step85:$sid",
				"",
				"level6_step86=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step86_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step86=$level6_step86:$sid",
				"",
				"level6_step87=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step87_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step87=$level6_step87:$sid",
				"",
				"level6_step88=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step88_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step88=$level6_step88:$sid",
				"",
				"level6_step89=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step89_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step89=$level6_step89:$sid",
				"",
				"level6_step90=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step90_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step90=$level6_step90:$sid",
				"",
				"level6_step91=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step91_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step91=$level6_step91:$sid",
				"",
				"level6_step92=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step92_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step92=$level6_step92:$sid",
				"",
				"level6_step93=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step93_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step93=$level6_step93:$sid",
				"",
				"level6_step94=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step94_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step94=$level6_step94:$sid",
				"",
				"level6_step95=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step95_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step95=$level6_step95:$sid",
				"",
				"level6_step96=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step96_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step96=$level6_step96:$sid",
				"",
				"level6_step97=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step97_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step97=$level6_step97:$sid",
				"",
				"level6_step98=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step98_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step98=$level6_step98:$sid",
				"",
				"level6_step99=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step99_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step99=$level6_step99:$sid",
				"",
				"level6_step100=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step100_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step100=$level6_step100:$sid",
				"",
				"level6_step101=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step101_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step101=$level6_step101:$sid",
				"",
				"level6_step102=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step102_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step102=$level6_step102:$sid",
				"",
				"level6_step103=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step103_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step103=$level6_step103:$sid",
				"",
				"level6_step104=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step104_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step104=$level6_step104:$sid",
				"",
				"level6_step105=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step105_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step105=$level6_step105:$sid",
				"",
				"level6_step106=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step106_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step106=$level6_step106:$sid",
				"",
				"level6_step107=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step107_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step107=$level6_step107:$sid",
				"",
				"level6_step108=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step108_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step108=$level6_step108:$sid",
				"",
				"level6_step109=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step109_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step109=$level6_step109:$sid",
				"",
				"level6_step110=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step110_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step110=$level6_step110:$sid",
				"",
				"level6_step111=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step111_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step111=$level6_step111:$sid",
				"",
				"level6_step112=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step112_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step112=$level6_step112:$sid",
				"",
				"level6_step113=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step113_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step113=$level6_step113:$sid",
				"",
				"level6_step114=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step114_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step114=$level6_step114:$sid",
				"",
				"level6_step115=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step115_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step115=$level6_step115:$sid",
				"",
				"level6_step116=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step116_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step116=$level6_step116:$sid",
				"",
				"level6_step117=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step117_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step117=$level6_step117:$sid",
				"",
				"level6_step118=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step118_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step118=$level6_step118:$sid",
				"",
				"level6_step119=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step119_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step119=$level6_step119:$sid",
				"",
				"level6_step120=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step120_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step120=$level6_step120:$sid",
				"",
				"level6_step121=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step121_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step121=$level6_step121:$sid",
				"",
				"level6_step122=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step122_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step122=$level6_step122:$sid",
				"",
				"level6_step123=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step123_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step123=$level6_step123:$sid",
				"",
				"level6_step124=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step124_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step124=$level6_step124:$sid",
				"",
				"level6_step125=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step125_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step125=$level6_step125:$sid",
				"",
				"level6_step126=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step126_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step126=$level6_step126:$sid",
				"",
				"level6_step127=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step127_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step127=$level6_step127:$sid",
				"",
				"level6_step128=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step128_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step128=$level6_step128:$sid",
				"",
				"level6_step129=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step129_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step129=$level6_step129:$sid",
				"",
				"level6_step130=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step130_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step130=$level6_step130:$sid",
				"",
				"level6_step131=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step131_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step131=$level6_step131:$sid",
				"",
				"level6_step132=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step132_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step132=$level6_step132:$sid",
				"",
				"level6_step133=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step133_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step133=$level6_step133:$sid",
				"",
				"level6_step134=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step134_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step134=$level6_step134:$sid",
				"",
				"level6_step135=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step135_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step135=$level6_step135:$sid",
				"",
				"level6_step136=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step136_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step136=$level6_step136:$sid",
				"",
				"level6_step137=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step137_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step137=$level6_step137:$sid",
				"",
				"level6_step138=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step138_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step138=$level6_step138:$sid",
				"",
				"level6_step139=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step139_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step139=$level6_step139:$sid",
				"",
				"level6_step140=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step140_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step140=$level6_step140:$sid",
				"",
				"level6_step141=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step141_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step141=$level6_step141:$sid",
				"",
				"level6_step142=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step142_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step142=$level6_step142:$sid",
				"",
				"level6_step143=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step143_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step143=$level6_step143:$sid",
				"",
				"level6_step144=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step144_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step144=$level6_step144:$sid",
				"",
				"level6_step145=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step145_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step145=$level6_step145:$sid",
				"",
				"level6_step146=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step146_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step146=$level6_step146:$sid",
				"",
				"level6_step147=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step147_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step147=$level6_step147:$sid",
				"",
				"level6_step148=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step148_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step148=$level6_step148:$sid",
				"",
				"level6_step149=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step149_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step149=$level6_step149:$sid",
				"",
				"level6_step150=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step150_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step150=$level6_step150:$sid",
				"",
				"level6_step151=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step151_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step151=$level6_step151:$sid",
				"",
				"level6_step152=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step152_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step152=$level6_step152:$sid",
				"",
				"level6_step153=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step153_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step153=$level6_step153:$sid",
				"",
				"level6_step154=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step154_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step154=$level6_step154:$sid",
				"",
				"level6_step155=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step155_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step155=$level6_step155:$sid",
				"",
				"level6_step156=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step156_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step156=$level6_step156:$sid",
				"",
				"level6_step157=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step157_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step157=$level6_step157:$sid",
				"",
				"level6_step158=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step158_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step158=$level6_step158:$sid",
				"",
				"level6_step159=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step159_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step159=$level6_step159:$sid",
				"",
				"level6_step160=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step160_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step160=$level6_step160:$sid",
				"",
				"level6_step161=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step161_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step161=$level6_step161:$sid",
				"",
				"level6_step162=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step162_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step162=$level6_step162:$sid",
				"",
				"level6_step163=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step163_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step163=$level6_step163:$sid",
				"",
				"level6_step164=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step164_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step164=$level6_step164:$sid",
				"",
				"level6_step165=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step165_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step165=$level6_step165:$sid",
				"",
				"level6_step166=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step166_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step166=$level6_step166:$sid",
				"",
				"level6_step167=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step167_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step167=$level6_step167:$sid",
				"",
				"level6_step168=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step168_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step168=$level6_step168:$sid",
				"",
				"level6_step169=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step169_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step169=$level6_step169:$sid",
				"",
				"level6_step170=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step170_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step170=$level6_step170:$sid",
				"",
				"level6_step171=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step171_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step171=$level6_step171:$sid",
				"",
				"level6_step172=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step172_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step172=$level6_step172:$sid",
				"",
				"level6_step173=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step173_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step173=$level6_step173:$sid",
				"",
				"level6_step174=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step174_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step174=$level6_step174:$sid",
				"",
				"level6_step175=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step175_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step175=$level6_step175:$sid",
				"",
				"level6_step176=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step176_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step176=$level6_step176:$sid",
				"",
				"level6_step177=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step177_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step177=$level6_step177:$sid",
				"",
				"level6_step178=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step178_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step178=$level6_step178:$sid",
				"",
				"level6_step179=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step179_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step179=$level6_step179:$sid",
				"",
				"level6_step180=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step180_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step180=$level6_step180:$sid",
				"",
				"level6_step181=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step181_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step181=$level6_step181:$sid",
				"",
				"level6_step182=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step182_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step182=$level6_step182:$sid",
				"",
				"level6_step183=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step183_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step183=$level6_step183:$sid",
				"",
				"level6_step184=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step184_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step184=$level6_step184:$sid",
				"",
				"level6_step185=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step185_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step185=$level6_step185:$sid",
				"",
				"level6_step186=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step186_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step186=$level6_step186:$sid",
				"",
				"level6_step187=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step187_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step187=$level6_step187:$sid",
				"",
				"level6_step188=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step188_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step188=$level6_step188:$sid",
				"",
				"level6_step189=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step189_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step189=$level6_step189:$sid",
				"",
				"level6_step190=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step190_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step190=$level6_step190:$sid",
				"",
				"level6_step191=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step191_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step191=$level6_step191:$sid",
				"",
				"level6_step192=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step192_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step192=$level6_step192:$sid",
				"",
				"level6_step193=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step193_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step193=$level6_step193:$sid",
				"",
				"level6_step194=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step194_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step194=$level6_step194:$sid",
				"",
				"level6_step195=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step195_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step195=$level6_step195:$sid",
				"",
				"level6_step196=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step196_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step196=$level6_step196:$sid",
				"",
				"level6_step197=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step197_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step197=$level6_step197:$sid",
				"",
				"level6_step198=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step198_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step198=$level6_step198:$sid",
				"",
				"level6_step199=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step199_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step199=$level6_step199:$sid",
				"",
				"level6_step200=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step200_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step200=$level6_step200:$sid",
				"",
				"level6_step201=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step201_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step201=$level6_step201:$sid",
				"",
				"level6_step202=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step202_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step202=$level6_step202:$sid",
				"",
				"level6_step203=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step203_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step203=$level6_step203:$sid",
				"",
				"level6_step204=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step204_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step204=$level6_step204:$sid",
				"",
				"level6_step205=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step205_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step205=$level6_step205:$sid",
				"",
				"level6_step206=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step206_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step206=$level6_step206:$sid",
				"",
				"level6_step207=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step207_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step207=$level6_step207:$sid",
				"",
				"level6_step208=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step208_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step208=$level6_step208:$sid",
				"",
				"level6_step209=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step209_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step209=$level6_step209:$sid",
				"",
				"level6_step210=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step210_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step210=$level6_step210:$sid",
				"",
				"level6_step211=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step211_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step211=$level6_step211:$sid",
				"",
				"level6_step212=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step212_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step212=$level6_step212:$sid",
				"",
				"level6_step213=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step213_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step213=$level6_step213:$sid",
				"",
				"level6_step214=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step214_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step214=$level6_step214:$sid",
				"",
				"level6_step215=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step215_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step215=$level6_step215:$sid",
				"",
				"level6_step216=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step216_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step216=$level6_step216:$sid",
				"",
				"level6_step217=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step217_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step217=$level6_step217:$sid",
				"",
				"level6_step218=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step218_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step218=$level6_step218:$sid",
				"",
				"level6_step219=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step219_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step219=$level6_step219:$sid",
				"",
				"level6_step220=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step220_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step220=$level6_step220:$sid",
				"",
				"level6_step221=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step221_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step221=$level6_step221:$sid",
				"",
				"level6_step222=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step222_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step222=$level6_step222:$sid",
				"",
				"level6_step223=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step223_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step223=$level6_step223:$sid",
				"",
				"level6_step224=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step224_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step224=$level6_step224:$sid",
				"",
				"level6_step225=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step225_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step225=$level6_step225:$sid",
				"",
				"level6_step226=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step226_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step226=$level6_step226:$sid",
				"",
				"level6_step227=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step227_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step227=$level6_step227:$sid",
				"",
				"level6_step228=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step228_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step228=$level6_step228:$sid",
				"",
				"level6_step229=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step229_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step229=$level6_step229:$sid",
				"",
				"level6_step230=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step230_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step230=$level6_step230:$sid",
				"",
				"level6_step231=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step231_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step231=$level6_step231:$sid",
				"",
				"level6_step232=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step232_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step232=$level6_step232:$sid",
				"",
				"level6_step233=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step233_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step233=$level6_step233:$sid",
				"",
				"level6_step234=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step234_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step234=$level6_step234:$sid",
				"",
				"level6_step235=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step235_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step235=$level6_step235:$sid",
				"",
				"level6_step236=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step236_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step236=$level6_step236:$sid",
				"",
				"level6_step237=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step237_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step237=$level6_step237:$sid",
				"",
				"level6_step238=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step238_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step238=$level6_step238:$sid",
				"",
				"level6_step239=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step239_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step239=$level6_step239:$sid",
				"",
				"level6_step240=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step240_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step240=$level6_step240:$sid",
				"",
				"level6_step241=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step241_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step241=$level6_step241:$sid",
				"",
				"level6_step242=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step242_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step242=$level6_step242:$sid",
				"",
				"level6_step243=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step243_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step243=$level6_step243:$sid",
				"",
				"level6_step244=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step244_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step244=$level6_step244:$sid",
				"",
				"level6_step245=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step245_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step245=$level6_step245:$sid",
				"",
				"level6_step246=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step246_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step246=$level6_step246:$sid",
				"",
				"level6_step247=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step247_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step247=$level6_step247:$sid",
				"",
				"level6_step248=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step248_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step248=$level6_step248:$sid",
				"",
				"level6_step249=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step249_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step249=$level6_step249:$sid",
				"",
				"level6_step250=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step250_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step250=$level6_step250:$sid",
				"",
				"level6_step251=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step251_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step251=$level6_step251:$sid",
				"",
				"level6_step252=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step252_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step252=$level6_step252:$sid",
				"",
				"level6_step253=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step253_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step253=$level6_step253:$sid",
				"",
				"level6_step254=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step254_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step254=$level6_step254:$sid",
				"",
				"level6_step255=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step255_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step255=$level6_step255:$sid",
				"",
				"level6_step256=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step256_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step256=$level6_step256:$sid",
				"",
				"level6_step257=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step257_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step257=$level6_step257:$sid",
				"",
				"level6_step258=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step258_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step258=$level6_step258:$sid",
				"",
				"level6_step259=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step259_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step259=$level6_step259:$sid",
				"",
				"level6_step260=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step260_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step260=$level6_step260:$sid",
				"",
				"level6_step261=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step261_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step261=$level6_step261:$sid",
				"",
				"level6_step262=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step262_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step262=$level6_step262:$sid",
				"",
				"level6_step263=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step263_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step263=$level6_step263:$sid",
				"",
				"level6_step264=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step264_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step264=$level6_step264:$sid",
				"",
				"level6_step265=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step265_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step265=$level6_step265:$sid",
				"",
				"level6_step266=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step266_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step266=$level6_step266:$sid",
				"",
				"level6_step267=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step267_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step267=$level6_step267:$sid",
				"",
				"level6_step268=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step268_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step268=$level6_step268:$sid",
				"",
				"level6_step269=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step269_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step269=$level6_step269:$sid",
				"",
				"level6_step270=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step270_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step270=$level6_step270:$sid",
				"",
				"level6_step271=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step271_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step271=$level6_step271:$sid",
				"",
				"level6_step272=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step272_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step272=$level6_step272:$sid",
				"",
				"level6_step273=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step273_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step273=$level6_step273:$sid",
				"",
				"level6_step274=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step274_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step274=$level6_step274:$sid",
				"",
				"level6_step275=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step275_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step275=$level6_step275:$sid",
				"",
				"level6_step276=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step276_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step276=$level6_step276:$sid",
				"",
				"level6_step277=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step277_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step277=$level6_step277:$sid",
				"",
				"level6_step278=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step278_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step278=$level6_step278:$sid",
				"",
				"level6_step279=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step279_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step279=$level6_step279:$sid",
				"",
				"level6_step280=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step280_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step280=$level6_step280:$sid",
				"",
				"level6_step281=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step281_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step281=$level6_step281:$sid",
				"",
				"level6_step282=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step282_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step282=$level6_step282:$sid",
				"",
				"level6_step283=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step283_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step283=$level6_step283:$sid",
				"",
				"level6_step284=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step284_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step284=$level6_step284:$sid",
				"",
				"level6_step285=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step285_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step285=$level6_step285:$sid",
				"",
				"level6_step286=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step286_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step286=$level6_step286:$sid",
				"",
				"level6_step287=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step287_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step287=$level6_step287:$sid",
				"",
				"level6_step288=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step288_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step288=$level6_step288:$sid",
				"",
				"level6_step289=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step289_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step289=$level6_step289:$sid",
				"",
				"level6_step290=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step290_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step290=$level6_step290:$sid",
				"",
				"level6_step291=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step291_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step291=$level6_step291:$sid",
				"",
				"level6_step292=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step292_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step292=$level6_step292:$sid",
				"",
				"level6_step293=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step293_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step293=$level6_step293:$sid",
				"",
				"level6_step294=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step294_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step294=$level6_step294:$sid",
				"",
				"level6_step295=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step295_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step295=$level6_step295:$sid",
				"",
				"level6_step296=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step296_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step296=$level6_step296:$sid",
				"",
				"level6_step297=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step297_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step297=$level6_step297:$sid",
				"",
				"level6_step298=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step298_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step298=$level6_step298:$sid",
				"",
				"level6_step299=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step299_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step299=$level6_step299:$sid",
				"",
				"level6_step300=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step300_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step300=$level6_step300:$sid",
				"",
				"level6_step301=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step301_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step301=$level6_step301:$sid",
				"",
				"level6_step302=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step302_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step302=$level6_step302:$sid",
				"",
				"level6_step303=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step303_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step303=$level6_step303:$sid",
				"",
				"level6_step304=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step304_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step304=$level6_step304:$sid",
				"",
				"level6_step305=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step305_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step305=$level6_step305:$sid",
				"",
				"level6_step306=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step306_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step306=$level6_step306:$sid",
				"",
				"level6_step307=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step307_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step307=$level6_step307:$sid",
				"",
				"level6_step308=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step308_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step308=$level6_step308:$sid",
				"",
				"level6_step309=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step309_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step309=$level6_step309:$sid",
				"",
				"level6_step310=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step310_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step310=$level6_step310:$sid",
				"",
				"level6_step311=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step311_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step311=$level6_step311:$sid",
				"",
				"level6_step312=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step312_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step312=$level6_step312:$sid",
				"",
				"level6_step313=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step313_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step313=$level6_step313:$sid",
				"",
				"level6_step314=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step314_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step314=$level6_step314:$sid",
				"",
				"level6_step315=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step315_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step315=$level6_step315:$sid",
				"",
				"level6_step316=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step316_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step316=$level6_step316:$sid",
				"",
				"level6_step317=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step317_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step317=$level6_step317:$sid",
				"",
				"level6_step318=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step318_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step318=$level6_step318:$sid",
				"",
				"level6_step319=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step319_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step319=$level6_step319:$sid",
				"",
				"level6_step320=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step320_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step320=$level6_step320:$sid",
				"",
				"level6_step321=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step321_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step321=$level6_step321:$sid",
				"",
				"level6_step322=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step322_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step322=$level6_step322:$sid",
				"",
				"level6_step323=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step323_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step323=$level6_step323:$sid",
				"",
				"level6_step324=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step324_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step324=$level6_step324:$sid",
				"",
				"level6_step325=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step325_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step325=$level6_step325:$sid",
				"",
				"level6_step326=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step326_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step326=$level6_step326:$sid",
				"",
				"level6_step327=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step327_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step327=$level6_step327:$sid",
				"",
				"level6_step328=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step328_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step328=$level6_step328:$sid",
				"",
				"level6_step329=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step329_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step329=$level6_step329:$sid",
				"",
				"level6_step330=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step330_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step330=$level6_step330:$sid",
				"",
				"level6_step331=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step331_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step331=$level6_step331:$sid",
				"",
				"level6_step332=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step332_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step332=$level6_step332:$sid",
				"",
				"level6_step333=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step333_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step333=$level6_step333:$sid",
				"",
				"level6_step334=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step334_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step334=$level6_step334:$sid",
				"",
				"level6_step335=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step335_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step335=$level6_step335:$sid",
				"",
				"level6_step336=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step336_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step336=$level6_step336:$sid",
				"",
				"level6_step337=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step337_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step337=$level6_step337:$sid",
				"",
				"level6_step338=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step338_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step338=$level6_step338:$sid",
				"",
				"level6_step339=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step339_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step339=$level6_step339:$sid",
				"",
				"level6_step340=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step340_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step340=$level6_step340:$sid",
				"",
				"level6_step341=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step341_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step341=$level6_step341:$sid",
				"",
				"level6_step342=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step342_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step342=$level6_step342:$sid",
				"",
				"level6_step343=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step343_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step343=$level6_step343:$sid",
				"",
				"level6_step344=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step344_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step344=$level6_step344:$sid",
				"",
				"level6_step345=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step345_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step345=$level6_step345:$sid",
				"",
				"level6_step346=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step346_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step346=$level6_step346:$sid",
				"",
				"level6_step347=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step347_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step347=$level6_step347:$sid",
				"",
				"level6_step348=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step348_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step348=$level6_step348:$sid",
				"",
				"level6_step349=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step349_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step349=$level6_step349:$sid",
				"",
				"level6_step350=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step350_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step350=$level6_step350:$sid",
				"",
				"level6_step351=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step351_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step351=$level6_step351:$sid",
				"",
				"level6_step352=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step352_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step352=$level6_step352:$sid",
				"",
				"level6_step353=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step353_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step353=$level6_step353:$sid",
				"",
				"level6_step354=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step354_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step354=$level6_step354:$sid",
				"",
				"level6_step355=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step355_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step355=$level6_step355:$sid",
				"",
				"level6_step356=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step356_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step356=$level6_step356:$sid",
				"",
				"level6_step357=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step357_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step357=$level6_step357:$sid",
				"",
				"level6_step358=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step358_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step358=$level6_step358:$sid",
				"",
				"level6_step359=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step359_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step359=$level6_step359:$sid",
				"",
				"level6_step360=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step360_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step360=$level6_step360:$sid",
				"",
				"level6_step361=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step361_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step361=$level6_step361:$sid",
				"",
				"level6_step362=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step362_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step362=$level6_step362:$sid",
				"",
				"level6_step363=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step363_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step363=$level6_step363:$sid",
				"",
				"level6_step364=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step364_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step364=$level6_step364:$sid",
				"",
				"level6_step365=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step365_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step365=$level6_step365:$sid",
				"",
				"level6_step366=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step366_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step366=$level6_step366:$sid",
				"",
				"level6_step367=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step367_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step367=$level6_step367:$sid",
				"",
				"level6_step368=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step368_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step368=$level6_step368:$sid",
				"",
				"level6_step369=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step369_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step369=$level6_step369:$sid",
				"",
				"level6_step370=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step370_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step370=$level6_step370:$sid",
				"",
				"level6_step371=\"-d afterok\"",
				"sresult=`sbatch $level5_step4 level6_step371_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step371=$level6_step371:$sid",
				"",
				"level6_step372=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step372_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step372=$level6_step372:$sid",
				"",
				"level6_step373=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step373_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step373=$level6_step373:$sid",
				"",
				"level6_step374=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step374_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step374=$level6_step374:$sid",
				"",
				"level6_step375=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step375_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step375=$level6_step375:$sid",
				"",
				"level6_step376=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step376_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step376=$level6_step376:$sid",
				"",
				"level6_step377=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step377_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step377=$level6_step377:$sid",
				"",
				"level6_step378=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step378_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step378=$level6_step378:$sid",
				"",
				"level6_step379=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step379_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step379=$level6_step379:$sid",
				"",
				"level6_step380=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step380_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step380=$level6_step380:$sid",
				"",
				"level6_step381=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step381_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step381=$level6_step381:$sid",
				"",
				"level6_step382=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step382_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step382=$level6_step382:$sid",
				"",
				"level6_step383=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step383_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step383=$level6_step383:$sid",
				"",
				"level6_step384=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step384_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step384=$level6_step384:$sid",
				"",
				"level6_step385=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step385_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step385=$level6_step385:$sid",
				"",
				"level6_step386=\"-d afterok\"",
				"sresult=`sbatch $level5_step2 level6_step386_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step386=$level6_step386:$sid",
				"",
				"level6_step387=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step387_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step387=$level6_step387:$sid",
				"",
				"level6_step388=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step388_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step388=$level6_step388:$sid",
				"",
				"level6_step389=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step389_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step389=$level6_step389:$sid",
				"",
				"level6_step390=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step390_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step390=$level6_step390:$sid",
				"",
				"level6_step391=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step391_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step391=$level6_step391:$sid",
				"",
				"level6_step392=\"-d afterok\"",
				"sresult=`sbatch $level5_step6 level6_step392_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step392=$level6_step392:$sid",
				"",
				"level6_step393=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step393_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step393=$level6_step393:$sid",
				"",
				"level6_step394=\"-d afterok\"",
				"sresult=`sbatch $level5_step9 level6_step394_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step394=$level6_step394:$sid",
				"",
				"level6_step395=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step395_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step395=$level6_step395:$sid",
				"",
				"level6_step396=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step396_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step396=$level6_step396:$sid",
				"",
				"level6_step397=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step397_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step397=$level6_step397:$sid",
				"",
				"level6_step398=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step398_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step398=$level6_step398:$sid",
				"",
				"level6_step399=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step399_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step399=$level6_step399:$sid",
				"",
				"level6_step400=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step400_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step400=$level6_step400:$sid",
				"",
				"level6_step401=\"-d afterok\"",
				"sresult=`sbatch $level5_step1 level6_step401_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step401=$level6_step401:$sid",
				"",
				"level6_step402=\"-d afterok\"",
				"sresult=`sbatch $level5_step7 level6_step402_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step402=$level6_step402:$sid",
				"",
				"level6_step403=\"-d afterok\"",
				"sresult=`sbatch $level5_step3 level6_step403_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step403=$level6_step403:$sid",
				"",
				"level6_step404=\"-d afterok\"",
				"sresult=`sbatch $level5_step8 level6_step404_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step404=$level6_step404:$sid",
				"",
				"level6_step405=\"-d afterok\"",
				"sresult=`sbatch $level5_step5 level6_step405_part1.sh`",
				"echo $sresult",
				"sid=`echo $sresult | awk '{print $NF}'`",
				"level6_step405=$level6_step405:$sid",
				""])
		self.formatter.runSeveralSteps(search.writeCode())

		self.assertEqual(expected, self.buffer_stdout.getvalue())
